// Installing the MCP Bridge device into a Studio One profile.
import { cpSync, mkdirSync, writeFileSync, rmSync, existsSync, readFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { zipSync, unzipSync, strToU8, strFromU8 } from 'fflate';
import { mailboxDir } from '../paths.js';

export const deviceSource = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'device', 'StudioOneMCP');
export const deviceTarget = (profile) => join(profile, 'User Devices', 'studio-one-mcp');

// Studio One's own files store file URLs unencoded ("file:///…/Studio One/…").
export function fileUrl(path) {
  const p = path.replace(/\\/g, '/');
  return 'file://' + (p.startsWith('/') ? '' : '/') + p;
}

// The edit tasks ride in a user extension (Studio One does not scan a loose
// Scripts folder; an extension folder with scripts/<name>.package, a ZIP, is
// loaded at startup — checked on 5.5.2). Its task gives the bridge note editing.
export const editTasksSource = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'device', 'EditTasks');
export const editTasksTarget = (profile) => join(profile, 'Extensions', 'studio-one-mcp.edittasks');

export function editTasksPackage(mailbox = mailboxDir) {
  const files = {};
  const pkg = join(editTasksSource, 'package');
  for (const f of readdirSync(pkg)) files[f] = new Uint8Array(readFileSync(join(pkg, f)));
  files['McpEditConfig.js'] = strToU8(`// Generated by studio-one-mcp setup\nvar McpEditConfig = ${JSON.stringify({ mailbox: fileUrl(mailbox) + '/' })};\n`);
  return zipSync(files);
}

export function installEditTasks({ profile, mailbox = mailboxDir }) {
  const target = editTasksTarget(profile);
  mkdirSync(join(target, 'scripts'), { recursive: true });
  cpSync(join(editTasksSource, 'extension'), target, { recursive: true });
  writeFileSync(join(target, 'scripts', 'studio-one-mcp.package'), editTasksPackage(mailbox));
  return target;
}

export function installDevice({ profile, allowEval = false, mailbox = mailboxDir }) {
  const target = deviceTarget(profile);
  mkdirSync(target, { recursive: true });
  cpSync(deviceSource, target, { recursive: true });
  mkdirSync(mailbox, { recursive: true });
  const config = { mailbox: fileUrl(mailbox) + '/', allowEval: !!allowEval };
  writeFileSync(join(target, 'BridgeConfig.js'), `// Generated by studio-one-mcp setup\nvar BridgeConfig = ${JSON.stringify(config, null, 2)};\n`);
  const editTasks = installEditTasks({ profile, mailbox });
  return { target, config, editTasks };
}

export function uninstallDevice(profile) {
  const target = deviceTarget(profile);
  rmSync(target, { recursive: true, force: true });
  rmSync(editTasksTarget(profile), { recursive: true, force: true });
  return target;
}

export function readDeviceConfig(profile) {
  try {
    const text = readFileSync(join(deviceTarget(profile), 'BridgeConfig.js'), 'utf8');
    return JSON.parse(text.slice(text.indexOf('{'), text.lastIndexOf('}') + 1));
  } catch {
    return null;
  }
}

// The edit-task extension: installed if its package is there; current if its
// metadata and the package's files (all but the generated McpEditConfig.js)
// match this checkout.
export function editTasksStatus(profile) {
  const target = editTasksTarget(profile);
  const pkgFile = join(target, 'scripts', 'studio-one-mcp.package');
  if (!existsSync(pkgFile)) return { installed: false, current: false, stale: ['edit-task extension (not installed)'] };
  const stale = [];
  for (const f of readdirSync(join(editTasksSource, 'extension'))) {
    try {
      if (readFileSync(join(editTasksSource, 'extension', f), 'utf8') !== readFileSync(join(target, f), 'utf8')) stale.push(`Extensions/${f}`);
    } catch {
      stale.push(`Extensions/${f}`);
    }
  }
  let files = {};
  try {
    files = unzipSync(readFileSync(pkgFile));
  } catch {
    stale.push('edit-task package (unreadable)');
  }
  for (const f of readdirSync(join(editTasksSource, 'package'))) {
    const mine = readFileSync(join(editTasksSource, 'package', f), 'utf8');
    if (!files[f] || strFromU8(files[f]) !== mine) stale.push(`edit-task package: ${f}`);
  }
  return { installed: true, current: stale.length === 0, stale };
}

// installed: files present; current: identical to this checkout's device/ folder,
// with the edit-task extension present and current too.
export function deviceStatus(profile) {
  const target = deviceTarget(profile);
  const editTasks = editTasksStatus(profile);
  if (!existsSync(join(target, 'StudioOneMCP.device'))) return { installed: false, current: false, config: null, editTasks };
  const stale = readdirSync(deviceSource).filter((f) => {
    try {
      return readFileSync(join(deviceSource, f), 'utf8') !== readFileSync(join(target, f), 'utf8');
    } catch {
      return true;
    }
  });
  if (!editTasks.current) stale.push(...editTasks.stale);
  return { installed: true, current: stale.length === 0, stale, config: readDeviceConfig(profile), editTasks };
}
