#!/usr/bin/env node
// Copy the bridge device into Studio One's "User Devices" folder and write its
// config (mailbox location). Studio One must be restarted to see a new device;
// then add it once via Options → External Devices → Add… → studio-one-mcp / MCP Bridge.
//
//   node scripts/install-device.js [--profile <dir>] [--allow-eval] [--uninstall]
import { cpSync, mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { studioOneProfiles, mailboxDir } from '../src/paths.js';

const argv = process.argv.slice(2);
const flag = (f) => argv.includes(f);
const opt = (f) => (argv.includes(f) ? argv[argv.indexOf(f) + 1] : null);

const profile = opt('--profile') || studioOneProfiles()[0];
if (!profile || !existsSync(profile)) {
  console.error('Could not find a Studio One user profile. Pass --profile "<…/PreSonus/Studio One 5>".');
  process.exit(1);
}
const target = join(profile, 'User Devices', 'studio-one-mcp');

if (flag('--uninstall')) {
  rmSync(target, { recursive: true, force: true });
  console.log(`Removed ${target}. Also remove "MCP Bridge" from Options → External Devices.`);
  process.exit(0);
}

function fileUrl(path) {
  const p = path.replace(/\\/g, '/');
  return 'file://' + (p.startsWith('/') ? '' : '/') + p;
}

const src = join(dirname(fileURLToPath(import.meta.url)), '..', 'device', 'StudioOneMCP');
mkdirSync(target, { recursive: true });
cpSync(src, target, { recursive: true });
mkdirSync(mailboxDir, { recursive: true });

const config = {
  // Studio One's own files store file URLs unencoded ("file:///…/Studio One/…").
  mailbox: fileUrl(mailboxDir) + '/',
  allowEval: flag('--allow-eval'),
  pollMs: 100,
};
writeFileSync(join(target, 'BridgeConfig.js'), `// Generated by install-device.js\nvar BridgeConfig = ${JSON.stringify(config, null, 2)};\n`);

console.log(`Installed bridge device → ${target}`);
console.log(`Mailbox → ${mailboxDir}${config.allowEval ? '  (eval ENABLED)' : ''}`);
console.log('Next: restart Studio One, then Options → External Devices → Add… → studio-one-mcp → MCP Bridge (no MIDI ports needed).');
